export const ErrorCode = {
  // Token errors
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_USED: 'TOKEN_USED',

  // Session errors
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Site / key errors
  SITE_NOT_FOUND: 'SITE_NOT_FOUND',
  SITE_DISABLED: 'SITE_DISABLED',
  SITE_MISMATCH: 'SITE_MISMATCH',
  SITE_LIMIT_REACHED: 'SITE_LIMIT_REACHED',
  DOMAIN_ALREADY_REGISTERED: 'DOMAIN_ALREADY_REGISTERED',
  INVALID_SITE_KEY: 'INVALID_SITE_KEY',
  ORIGIN_NOT_ALLOWED: 'ORIGIN_NOT_ALLOWED',

  // Handoff errors
  HANDOFF_NOT_FOUND: 'HANDOFF_NOT_FOUND',

  // Auth / account errors
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  // Input errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CONFIRMATION: 'INVALID_CONFIRMATION',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',

  // Server errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
